namespace DevelopmentHell.Hubba.Models.Tests
{
    public enum Databases
    {
        USERS,
        LOGS,
        NOTIFICATIONS,
        PROJECTSHOWCASES
    }

    public enum Tables
    {
        RECOVERY_REQUESTS, USER_ACCOUNTS, USER_LOGINS, USER_OTPS,
        LOGS,
        NOTIFICATION_SETTINGS, USER_NOTIFICATIONS,
        SHOWCASES, SHOWCASEVOTES, SHOWCASECOMMENTS, SHOWCASEREPORTS, SHOWCASECOMMENTVOTES, SHOWCASECOMMENTREPORTS
    }
}
